### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by positron96** [nviennot/turbo-resin#13]
Hi, just want to ask whether the project is still in development? Am I right that it cannot yet replace original firmware for day-to-day jobs (as I see no "Control UV light" checkmark in README)?

**Comment by nviennot** [comment]
Sadly it is not,
You are correct, it is not functional

**Comment by positron96** [comment]
Ok, thanks for your work! When I have another printer and a lot of spare time, I might try my own take on open source firmware, but in C/C++ for a larger pool of embedded developers to pick the project up.
